language: node_js
node_js:
  - node
branches:
  only:
    - master
cache: node_modules
script:
  - yarn lint
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
notifications:
  email: false